### ISSUE TITLE
Plex connector not working Chrome 48.0.2541.0 (Nightly Build)

### ISSUE THREAD

**Issue by j4cknife** [david-sabata/web-scrobbler#818]
from console on the ext.

Error in event handler for runtime.onMessage: TypeError: Cannot read property 'href' of undefined
    at chrome-extension://hhinaapppaileiechjoiifaancjggfjm/core/background/objects/song.js:56:42
    at chrome-extension://hhinaapppaileiechjoiifaancjggfjm/vendor/underscore-min.js:5:1657
    at j.some.j.any (chrome-extension://hhinaapppaileiechjoiifaancjggfjm/vendor/underscore-min.js:5:2187)
    at Function.j.find.j.detect (chrome-extension://hhinaapppaileiechjoiifaancjggfjm/vendor/underscore-min.js:5:1628)
    at chrome-extension://hhinaapppaileiechjoiifaancjggfjm/core/background/objects/song.js:54:13
    at chrome-extension://hhinaapppaileiechjoiifaancjggfjm/vendor/underscore-min.js:5:1657
    at j.some.j.any (chrome-extension://hhinaapppaileiechjoiifaancjggfjm/vendor/underscore-min.js:5:2187)
    at Function.j.find.j.detect (chrome-extension://hhinaapppaileiechjoiifaancjggfjm/vendor/underscore-min.js:5:1628)handler @ extensions::uncaught_exception_handler:8exports.handle @ extensions::uncaught_exception_handler:100EventImpl.dispatch_ @ extensions::event_bindings:376EventImpl.dispatch @ extensions::event_bindings:393target.(anonymous function) @ extensions::SafeBuiltins:19publicClass.(anonymous function) @ extensions::utils:94messageListener @ extensions::messaging:179target.(anonymous function) @ extensions::SafeBuiltins:19EventImpl.dispatchToListener @ extensions::event_bindings:387target.(anonymous function) @ extensions::SafeBuiltins:19publicClass.(anonymous function) @ extensions::utils:94EventImpl.dispatch_ @ extensions::event_bindings:371EventImpl.dispatch @ extensions::event_bindings:393target.(anonymous function) @ extensions::SafeBuiltins:19publicClass.(anonymous function) @ extensions::utils:94dispatchOnMessage @ extensions::messaging:310

Let me know if i

**Comment by fedorg** [comment]
It's fixed in #809.
