### ISSUE TITLE
Amazon Web Player (music.amazon.co.uk) not working

### ISSUE THREAD

**Issue by LeonardChallis** [david-sabata/web-scrobbler#998]
I've installed the plugin (1.57) on Chrome 51.0.2704.106 m

When I go to music.amazon.co.uk to play Amazon Prime Music tracks the icon doesn't show up in red. No output is sent to the console at all. I tried adding music.co.uk.amazon as a URL pattern, but this came back with the following error:

```
Error in response to storage.get: TypeError: Cannot read property 'test' of null
    at chrome-extension://hhinaapppaileiechjoiifaancjggfjm/core/background/inject.js:148:47
    at chrome-extension://hhinaapppaileiechjoiifaancjggfjm/core/background/inject.js:147:14
    at onPatternsReady (chrome-extension://hhinaapppaileiechjoiifaancjggfjm/core/background/inject.js:138:31)
    at Object.callback (chrome-extension://hhinaapppaileiechjoiifaancjggfjm/core/background/chromeStorage.js:26:6)
    at Namespace.get (chrome-extension://hhinaapppaileiechjoiifaancjggfjm/core/background/chromeStorage.js:19:25)
    at Object.getAllPatterns (chrome-extension://hhinaapppaileiechjoiifaancjggfjm/core/background/customPatterns.js:7:12)
    at Object.onTabsUpdated (chrome-extension://hhinaapppaileiechjoiifaancjggfjm/core/background/inject.js:173:18)
    at chrome-extension://hhinaapppaileiechjoiifaancjggfjm/core/background/main.js:190:10handler @ extensions::uncaught_exception_handler:8(anonymous function) @ extensions::uncaught_exception_handler:100safeCallbackApply @ extensions::sendRequest:23handleResponse @ extensions::sendRequest:74
```

I tried it on YouTube and the icon goes red and the console has the expected `-- loaded for the first time...` etc.

Is there another way to listen to Amazon Prime Music? Or to make this URL work with the plugin?

**Comment by Paszt** [comment]
This has been fixed in #949.
